FROM archlinux:base

# Update system and install essentials
RUN pacman -Syu --noconfirm && \
    pacman -S --noconfirm \
        python \
        python-pip \
        base-devel \
        git \
        grep \
        findutils \
        bash \
	emacs \
    && pacman -Scc --noconfirm

# Create workspace directory
RUN mkdir -p /workspace
WORKDIR /workspace

# Keep container alive
CMD ["sleep", "infinity"]
