#!/bin/bash
# Interactive setup script for deployment configuration

set -e

echo "=== Assist Deployment Setup ==="
echo ""

# Check if .deploy.env already exists
if [ -f .deploy.env ]; then
    echo "⚠️  .deploy.env already exists!"
    read -p "Overwrite? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Aborted."
        exit 0
    fi
fi

# Get configuration from user
echo "Please provide the following information:"
echo ""

read -p "SSH host alias (e.g., assist-prod): " DEPLOY_HOST
read -p "Remote deployment path (e.g., /opt/assist): " DEPLOY_PATH
read -p "Service name (e.g., assist-web): " SERVICE_NAME
read -p "Data directory (e.g., /var/lib/assist/threads): " ASSIST_THREADS_DIR
read -p "Port (e.g., 8000): " ASSIST_PORT
read -p "Python command on remote (e.g., python3.14): " PYTHON

# Use defaults if empty
DEPLOY_HOST=${DEPLOY_HOST:-assist-prod}
DEPLOY_PATH=${DEPLOY_PATH:-/opt/assist}
SERVICE_NAME=${SERVICE_NAME:-assist-web}
ASSIST_THREADS_DIR=${ASSIST_THREADS_DIR:-/var/lib/assist/threads}
ASSIST_PORT=${ASSIST_PORT:-8000}
PYTHON=${PYTHON:-python3.14}

# Write .deploy.env
cat > .deploy.env <<EOF
# Deployment Configuration
# Generated by setup-deploy.sh

# SSH host alias (defined in ~/.ssh/config)
DEPLOY_HOST=$DEPLOY_HOST

# Remote deployment path
DEPLOY_PATH=$DEPLOY_PATH

# Service name (for systemd)
SERVICE_NAME=$SERVICE_NAME

# Environment variables for the service
ASSIST_THREADS_DIR=$ASSIST_THREADS_DIR
ASSIST_PORT=$ASSIST_PORT

# Python version on remote server
PYTHON=$PYTHON
EOF

echo ""
echo "✓ Created .deploy.env"
echo ""
echo "Next steps:"
echo ""
echo "1. Configure SSH host in ~/.ssh/config:"
echo ""
echo "   Host $DEPLOY_HOST"
echo "       HostName YOUR_SERVER_IP"
echo "       User YOUR_USERNAME"
echo "       IdentityFile ~/.ssh/id_rsa"
echo ""
echo "2. Test SSH connection:"
echo "   ssh $DEPLOY_HOST"
echo ""
echo "3. Create deployment directory on remote:"
echo "   ssh $DEPLOY_HOST 'sudo mkdir -p $DEPLOY_PATH && sudo chown \$USER:\$USER $DEPLOY_PATH'"
echo ""
echo "4. Deploy:"
echo "   make deploy-code"
echo "   make install-prod"
echo "   make deploy-service"
echo "   make restart"
echo ""
echo "5. Or use the full deployment command:"
echo "   make deploy"
echo ""
