#!/bin/sh
# Activate virtual environment and start server with default persistent index database.
set -e

. "$(dirname "$0")/../.venv/bin/activate"
exec python -m assist.server --index-db ~/.cache/assist/dbs
